name: pomodoro
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color: any
  google_maps_flutter: ^0.5.7
  cloud_firestore: ^0.9.13+1
  firebase_storage: 2.1.1+2
  flutter_rating_bar: ^1.1.1
  carousel_slider: ^1.3.0
  url_launcher: ^5.0.2
  http: ^0.12.0+2
  circular_bottom_navigation: ^1.0.0
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+2
  path_provider: ^0.5.0+1
  curved_navigation_bar: ^0.2.1
  image_picker: ^0.6.0+8
  image_cropper:
  cached_network_image: ^0.7.0
  camera: ^0.5.2+1
  shared_preferences: ^0.4.3
  image: 2.0.7
  flutter_launcher_icons: 0.7.0
  flutter_local_notifications:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  path:
  fluttertoast: ^3.1.0

  cupertino_icons: ^0.1.2
  intro_slider: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resource/temp.png
    - resource/data.json
    - resource/read1.jpg
    - resource/read3.jpg
    - resource/load1.png
    - resource/place1.jpg
    - resource/profile.png
    - resource/Label_book.png
    - resource/Label_Place.png
    - resource/Label_timer_2.png
    - resource/book_reviews.png
    - resource/book.png
    - resource/building.png
    - resource/timer.png
    
    - assets/animated/train_animated.gif
    - assets/animated/train_animated_circle.gif
    - assets/animated/train_circle.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Sukhumvit
      fonts:
        - asset: assets/fonts/sukhumvit-set/SukhumvitSet-Thin.ttf
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"